github.com:
    users:
        lesi-nedo:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: lesi-nedo
