exec-once = qs -c noctalia-shell
exec-once = systemctl --user start hyprpolkitagent
exec-once = ~/.config/hypr/scripts/pers_lock.sh &
exec-once = hypridle
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store
exec-once = /home/lesi-nedo/.config/hypr/scripts/rainbow_border.sh &
exec-once = sleep 2 && bash ~/.config/hypr/scripts/wall.sh &
