windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# windowrule = float, title:^(Picture-in-Picture)$
# windowrule = pin, title:^(Picture-in-Picture)$


windowrulev2 = float,class:^(ghosttyy)$,title:^(power_menu)$
windowrulev2 = size 40% 40%,class:^(ghosttyy)$,title:^(power_menu)$
windowrulev2 = move 30% 30%,class:^(ghosttyy)$,title:^(power_menu)$

