$wallpaper1 = /home/lesi-nedo/.local/share/wallpapers/wallhaven-gw7myq_3440x1440.png
$wallpaper2 = /home/lesi-nedo/.local/share/wallpapers/wallhaven-yq8k2d_2560x1080.png
$wallpaper3 = /home/lesi-nedo/.local/share/wallpapers/wallhaven-6loz9w_3440x1440.png
$wallpaper4 = /home/lesi-nedo/.local/share/wallpapers/wallhaven-pokg2e_3440x1440.png


# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
## wallpaper = monitor2,/path/to/next_image.png
# .. more monitors

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
